// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arexidcyfxcsfwcodtrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZXhpZGN5Znhjc2Z3Y29kdHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNzEzNTgsImV4cCI6MjA3OTY0NzM1OH0.RjZhhbO22H_286ZWDGEvQuqQwFPd8bcBhsrSEIV9TaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});